공간의 예약 가능 요일을 String이 아닌 Collection으로 가지도록 변경한다.
boardmarker-platform/Campus pull request #11
Opened 2024-01-08 10:52 UTC by carsago

코멘트로 의견을 달아놓을게요.

2024-01-08 10:57 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeks.kt
> +        }
```from()``` 쓰고 있어서 네이밍 임시 땡빵 했어요..

2024-01-08 10:57 UTC, carsago commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/SpaceValidatorTest.kt
> +        .toMutableList()
이 친구들 중복이 너무 많아서 Fixture에 넣든 해야될 거 같네요 
다른 이슈에서 Fixture 관련된 이야기하면서 같이 해도 괜찮을듯요

2024-01-08 10:57 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/feature/space/CreateSpace.kt
>      }
까먹었는데 이녀석도 중복코드라 다른 녀석한테 넘겨야겠어요.

2024-01-08 11:11 UTC, carsago commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeksTest.kt
> +    }
ParameterizedTest 같은거 찾아봤는데 의존성 받아야해요


---

https://veluxer62.github.io/tutorials/getting-started-with-kotest/
Data Driven Testing 부분

2024-01-08 11:15 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    private val enableDays: MutableList<DayOfWeeks>,
중복 검사 필요없게 순서보장이 되는 Set으로 할지가 고민이네요.

2024-01-08 23:31 UTC, woowahan-leah commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeksTest.kt
> +    }
List forEach를 활용하셔도 됩니다
```kotlin
DayOfWeeks.entries.forEach {
    // assertion
}
```

https://kotest.io/docs/framework/writing-tests.html#dynamic-tests

2024-01-10 06:04 UTC, Go-Jaecheol requested changes
오 바로 하셨네요!
코멘트 답변이랑 몇 가지 의견들 남겨놓았습니다~~

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeks.kt
> +        }
위에 `from()`이 더 이상 사용되지 않는다면 위에 저 코드 지우고 `from`으로 네이밍 해도 좋을 것 같아요

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeks.kt
> +        }
```suggestion
        fun create(weekday: String): DayOfWeeks {
            return requireNotNull(values().firstOrNull { it.name == weekday.uppercase() }) { "유효하지 않은 요일입니다." }
        }
```

`IllegalArgumentException` 직접 throw 하는 방법 말고 이렇게 `requireNotNull` 사용해도 될 것 같은데 이건 어떤가요??
사실 아직 어떤 방식이 더 코틀린스러운진 모르겠네요 🤣

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    private val enableDays: MutableList<DayOfWeeks>,
어차피 init에서 set으로 검증 과정 거친다면, 말씀하신 것처럼 순서 보장 되는 set 사용하는 것도 좋다고 생각합니다!

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    fun getEnableDays(): List<DayOfWeeks> = enableDays
`enableDays` 그대로 반환하는 기본 getter로 쓴다면
```kotlin
private val enableDays: MutableList<DayOfWeeks>
```
위에 `enableDays` 프로퍼티 선언하는 부분에서 private 없애고 `getEnableDays()` 없애고, 기존에 `getEnableDays()` 사용하던 부분들을 `.enableDays`로 프로퍼티 접근하도록 바꾸는 건 어떨까요..?
(사실 이렇게 해도 되는지 잘 몰라요.. 자바 코드로 디컴파일 해서 봤을 때 괜찮아 보이길래 말해봤슴다)

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/feature/space/CreateSpace.kt
>      }
좋습니다! 👍

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeksTest.kt
> +    }
감사합니다 레아! 😎

```suggestion
    "요일명이 올바르면 정상적으로 생성" {
       DayOfWeeks.entries.forEach {
            assertSoftly { beSuccess(DayOfWeeks.create(it.name)) }
        }
    }
```
이렇게 바꾸면 되겠네요

2024-01-10 06:04 UTC, Go-Jaecheol commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/SpaceValidatorTest.kt
> +        .toMutableList()
좋아용 💪

2024-01-10 09:56 UTC, carsago commented on backend/src/test/kotlin/com/woowahan/campus/zzimkkong/domain/DayOfWeeksTest.kt
> +    }
ㄱㅅ해요

2024-01-10 09:56 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    fun getEnableDays(): List<DayOfWeeks> = enableDays
이거 mutableList가 아니라 list로 넘기고싶은데 네이밍 컨벤션 어케해야할지 모르겠어서 고민했는데
```
@Entity
class Setting(
        ...
    private val _enableDays: MutableList<DayOfWeeks>,
        ...
) {

    val enableDays: List<DayOfWeeks> = _enableDays
```
이런 느낌으로 가면 될 것 같네용

https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties

2024-01-11 08:47 UTC, carsago reviewed
조금 더 바꾸어 보았어요.

2024-01-11 08:47 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    val _enableDays: SortedSet<DayOfWeeks>,
```@Column``` 명시 안해주면 _enable_days 컬럼에 쿼리 날려요

2024-01-11 08:47 UTC, carsago commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +        get() = _enableDays.toList()
SortedSet이 mutable해서 필드접근할땐 불변으로 넘겨보았어요.

2024-01-12 08:42 UTC, Go-Jaecheol commented on backend/src/main/kotlin/com/woowahan/campus/zzimkkong/domain/Setting.kt
> +    fun getEnableDays(): List<DayOfWeeks> = enableDays
오 이런 게 있었군요

2024-01-12 08:48 UTC, Go-Jaecheol approved these changes
멋진데요?? Backing Properties.. 하나 배워갑니다 😎

고생하셨어요~~~!

2024-01-13 05:17 UTC, merged